nota1 = float(input ("Nota do primeiro bimestre: "))
nota2 = float(input ("Nota do segundo bimestre: "))
nota3 = float(input ("Nota do terceiro bimestre: "))
nota4 = float(input ("Nota do quarto bimestre: "))
print ("A média das notas foi", (nota1+nota2+nota3+nota4)/4)